### ISSUE TITLE
QuantumKernelTrainer class optimizer not supporting bounds options. #570

### ISSUE THREAD

**Issue by OkuyanBoga** [OkuyanBoga/hc-qiskit-machine-learning#1]
Technical discussion for [#570](https://github.com/qiskit-community/qiskit-machine-learning/issues/570)

**Comment by OkuyanBoga** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QuantumKernelTrainer class optimizer not supporting bounds options. #570](https://trello.com/c/c8h9hNHR/2-quantumkerneltrainer-class-optimizer-not-supporting-bounds-options-570)

**Comment by edoaltamura** [comment]
The issue of conflicting bound options was correctly attributed to Qiskit algorithms https://github.com/qiskit-community/qiskit-algorithms/issues/57. Since this lies outside of the Qiskit machine-learning codebase, I fixed it separately here: https://github.com/edoaltamura/qiskit-algorithms/commit/bc4c98cd53e824c09cb0c9a726c69a867d31e029.
